// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/loaders/getall": {
            "get": {
                "description": "Отправляет всю таблицу с данными о каждом погрузчике",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Погрузчики"
                ],
                "summary": "Получить все погрузчики",
                "operationId": "all_loaders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Loader"
                            }
                        }
                    }
                }
            }
        },
        "/api/loaders/getimage/{loader_id}": {
            "get": {
                "description": "Отправляет всю таблицу с данными о каждом погрузчике",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/jpg",
                    " image/png"
                ],
                "tags": [
                    "Погрузчики"
                ],
                "summary": "Получить все погрузчики",
                "operationId": "loader_image",
                "parameters": [
                    {
                        "type": "string",
                        "example": "1",
                        "description": "ID погрузчика",
                        "name": "loader_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Loader": {
            "type": "object",
            "properties": {
                "autoWeight": {
                    "type": "integer"
                },
                "brakeType": {
                    "type": "string"
                },
                "chargingTime": {
                    "type": "string"
                },
                "engineType": {
                    "type": "string"
                },
                "forkLength": {
                    "type": "integer"
                },
                "frontWheels": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "hydraulicLiftingEngine": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "length": {
                    "type": "integer"
                },
                "liftHeight": {
                    "type": "integer"
                },
                "liftingAngle": {
                    "type": "integer"
                },
                "liftingCylinder": {
                    "type": "string"
                },
                "longmenFrameMaterial": {
                    "type": "integer"
                },
                "maxLiftWeight": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "picturePath": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "rearWheels": {
                    "type": "string"
                },
                "steeringMode": {
                    "type": "string"
                },
                "turningRadius": {
                    "type": "integer"
                },
                "voltage": {
                    "type": "integer"
                },
                "wheelAxis": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                },
                "workingHours": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите JWT токен",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gangchi API",
	Description:      "Документация к API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
